port: 4000
host: 0.0.0.0
safe: false

url: https://stillfollowers.app
enforce_ssl: stillfollowers.app

# ========== MAIN SITE ==============

# Site settings (Main)
title: Still Followers - Get Followers for Instagram, TikTok, Twitter and Mastodon
description: "Get followers analytics and organic growth! Available for Instagram, TikTok, Twitter and Mastodon! Download FREE on the App Store!"

# Opengraph (Main)
opengraph:
    title: 
    description:
    image: /assets/img/FBBanner.png
    height: 630
    width: 1200

# ========== TWITTER SITE ==============

# Site settings (Twitter)
title_twitter: Still Followers for Twitter - Smart Analytics and Growth for Twitter!
description_twitter: "Have you ever wondered how to grow on Twitter? Let Still Followers do the hard work... Get powerful tracking and analytics about your Twitter followers. Give up wasting your time... KEEP IT SHORT AND SIMPLE: Analytics well done!"

# Opengraph (Twitter)
opengraph_twitter:
    title:
    description: "Get followers analytics and organic growth for Twitter! Download FREE on the App Store!"
    image: /assets/img/twitter/FBBanner.png
    height: 630
    width: 1200

# App Setting (Twitter)
appstore_twitter_link: "https://apps.apple.com/app/apple-store/id1136209740?pt=674507&ct=web&mt=8"

# Favicons (Twitter)
favicon_twitter:     /assets/favicon/twitter/favicon.ico
touch_icon_twitter:  /assets/favicon/twitter/apple-touch-icon.png

# ========== INSTAGRAM SITE ==============

# Site settings (Instagram)
title_instagram: Still Followers for Instagram - Smart Analytics and Growth for Instagram!
description_instagram: "Have you ever wondered how to grow on Instagram? Let Still Followers do the hard work... Get powerful tracking and analytics about your Instagram followers. Give up wasting your time... KEEP IT SHORT AND SIMPLE: Analytics well done!"

# Opengraph (Instagram)
opengraph_instagram:
    title: 
    description: "Get followers analytics and organic growth for Instagram! Download FREE on the App Store!"
    image: /assets/img/instagram/FBBanner.png
    height: 630
    width: 1200

# App Setting (Instagram)
appstore_instagram_link: "https://apps.apple.com/app/apple-store/id1394497522?pt=674507&ct=web&mt=8"

# Favicons (Instagram)
favicon_instagram:     /assets/favicon/instagram/favicon.ico
touch_icon_instagram:  /assets/favicon/instagram/apple-touch-icon.png

# ========== TIKTOK SITE ==============

# Site settings (TikTok)
title_tiktok: Still Followers for TikTok - Smart Analytics and Growth for TikTok!
description_tiktok: "Have you ever wondered how to grow on TikTok? Let Still Followers do the hard work... Get powerful tracking and analytics about your TikTok followers. Give up wasting your time... KEEP IT SHORT AND SIMPLE: Analytics well done!"

# Opengraph (TikTok)
opengraph_tiktok:
    title: 
    description: "Get followers analytics and organic growth for TikTok! Download FREE on the App Store!"
    image: /assets/img/tiktok/FBBanner.png
    height: 630
    width: 1200

# App Setting (TikTok)
appstore_tiktok_link: "https://apps.apple.com/app/apple-store/id1518561859?pt=674507&ct=web&mt=8"

# Favicons (TikTok)
favicon_tiktok:     /assets/favicon/tiktok/favicon.ico
touch_icon_tiktok:  /assets/favicon/tiktok/apple-touch-icon.png

# ========== SHARED SETTINGS ==============

# User settings
username: Bobgoo S.L.
email_username: support@bobgoo.com
twitter_username: stillfollowers
instagram_username: stillfollowers
tiktok_username: stillfollowers

# Google-analytics
google_analytics_key: UA-25289053-13

# Favicons
favicon:     /assets/favicon/favicon.ico
touch_icon:  /assets/favicon/apple-touch-icon.png

exclude: ['package.json', 'src' , 'node_modules']
