port: 4000
host: 0.0.0.0
safe: false

url: https://stillfollowers.app
enforce_ssl: stillfollowers.app

# ========== MAIN SITE ==============

# Site settings (Main)
title: Still Followers - Get Followers for Instagram and Twitter
description: "Get followers for Twitter and Instagram NOW! Download the app for FREE!"

# Opengraph (Main)
opengraph:
    title: 
    description:
    image: /assets/img/FBBanner.png
    height: 630
    width: 1200

# ========== TWITTER SITE ==============

# Site settings (Twitter)
title_twitter: Still Followers for Twitter - Get Followers Now!
description_twitter: "Have you ever wondered how to grow on Twitter? Let Still Followers do the hard work... Get powerful tracking and analytics of your Twitter followers. Give up wasting your time... KEEP IT SHORT AND SIMPLE: Analytics well done!" 

# Opengraph (Twitter)
opengraph_twitter:
    title: 
    description:
    image: /assets/img/twitter/FBBanner.png
    height: 630
    width: 1200

# App Setting (Twitter)
appstore_twitter_link: "https://apps.apple.com/app/still-followers-for-twitter/id1136209740?mt=8"

# Favicons (Twitter)
favicon_twitter:     /assets/favicon/twitter/favicon.ico
touch_icon_twitter:  /assets/favicon/twitter/apple-touch-icon.png

# ========== INSTAGRAM SITE ==============

# Site settings (Instagram)
title_instagram: Still Followers for Instagram - Get Followers Now!
description_instagram: "Have you ever wondered how to grow on Instagram? Let Still Followers do the hard work... Get powerful tracking and analytics of your Instagram followers. Give up wasting your time... KEEP IT SHORT AND SIMPLE: Analytics well done!" 

# Opengraph (Instagram)
opengraph_instagram:
    title: 
    description:
    image: /assets/img/instagram/FBBanner.png
    height: 630
    width: 1200

# App Setting (Instagram)
appstore_instagram_link: "https://apps.apple.com/app/still-followers-for-instagram/id1394497522?mt=8"

# Favicons (Instagram)
favicon_instagram:     /assets/favicon/instagram/favicon.ico
touch_icon_instagram:  /assets/favicon/instagram/apple-touch-icon.png

# ========== SHARED SETTINGS ==============

# User settings
username: Bobgoo
email_username: support@bobgoo.com
twitter_username: stillfollowers
instagram_username: stillfollowers

# Google-analytics
google_analytics_key: UA-25289053-13

# Favicons
favicon:     /assets/favicon/favicon.ico
touch_icon:  /assets/favicon/apple-touch-icon.png

exclude: ['package.json', 'src' , 'node_modules']
