port: 4000
host: 0.0.0.0
safe: false

url: https://stillfollowers.app
enforce_ssl: stillfollowers.app

# App Setting
appstore_instagram_link: "https://itunes.apple.com/app/apple-store/id1394497522?pt=674507&ct=web&mt=8"
appstore_twitter_link: "https://itunes.apple.com/app/apple-store/id1136209740?pt=674507ct=web&mt=8"

# User settings
username: Bobgoo, S.L
email_username: support@bobgoo.com
twitter_username: stillfollowers
instagram_username: stillfollowers

# Google-analytics
google_analytics_key: UA-25289053-12

# Opengraph
opengraph:
    title: 
    description:
    image: /assets/img/FBBanner.png
    height: 630
    width: 1200

# Favicons
favicon:     /assets/favicon/favicon.ico
touch_icon:  /assets/faviconapple-touch-icon.png

exclude: ['package.json', 'src' , 'node_modules']
